version: '3.8'

services:
  
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
  
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: backend/auth/Dockerfile
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      AUTH_DB: ${AUTH_DB}
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "80:80"
