version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB}
    ports:
      - "5432:5432"
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"

  backend:
    build: ./backend/auth
    environment:
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: postgresdb
      POSTGRES_DATABASE: ${AUTH_DB}
    ports:
      - "4000:4000"
    depends_on:
      - postgresdb
    entrypoint: ["sh", "./entrypoint.sh"]

  web:
    build: ./web
    ports:
      - "80:80"
